### ISSUE TITLE
If not email login, only the `session_token` require.

### ISSUE THREAD

**Issue by bluemoon37** [cooolr/chatgpt-proxy-web#8]
只使用 session_token
{"email_address": None, "password": None, "session_token": "eyJhbGciOiJkaXIiLNIJzNuFaMJByIOYn5p45LFyFOS2gUvvL_A1HIztw", "user": None},
[2023-03-09 14:26:00,570] ERROR in app: Exception on /chat/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "main.py", line 122, in index
    headers = user_headers[uid]
KeyError: 'cfa482'

**Comment by bluemoon37** [comment]
行了
